### ISSUE TITLE
Add Sound in R-Type Game

### ISSUE THREAD

**Issue by TomDUVAL-MAHE** [R-Type-Epitech-Nantes/R-Type#203]
For this issue you must create a new Shared Resource (S.R.) : 

- [x] Sound S.R.

This S.R. must contain an Enum which contains Sounds names.
This S.R. must contain a list of key EnumNames and Sounds

Add in This S.R. an add Sound function like addTexture in GraphicsTextureResource.hpp

For this issue you must create a new Component : 

- [x] Sound Component

This Component take a Sound Name (Enum)

**Comment by osvegn** [comment]
@TomDUVAL-MAHE What the sound component needs inside ?
