### ISSUE TITLE
Add Music in R-Type Game

### ISSUE THREAD

**Issue by TomDUVAL-MAHE** [R-Type-Epitech-Nantes/R-Type#204]
For this issue you must create a new Shared Resource (S.R.) : 

- [x] Music S.R.

This S.R. must contain an Enum which contains Musics name.
This S.R. must contain a list of key EnumNames and musics

Add in This S.R. an add Music function like addTexture in GraphicsTextureResource.hpp

For this issue you must create a new Component : 

- [x] Music Component

This Component take a Music Name (Enum)
This Component must contain an Enum Status which is Stopped or Paused or Playing

**Comment by osvegn** [comment]
@TomDUVAL-MAHE What the music component needs inside ?
