### ISSUE TITLE
Create Every Component

### ISSUE THREAD

**Issue by 31Nathan** [R-Type-Epitech-Nantes/R-Type#62]
For the ECS, we need a list of working components:

- [x] Size Component
- [x] Position Component
- [x] IsButton Component
- [x] Movement Component
- [x] Velocity Component
- [x] Shooting Frequency Component
- [x] IsControbable Component
- [x] ActionList Component
- [x] AttackBar Component (gonna need help on this one)
- [x] Life Component
- [x] Damage Component
- [x] Lifetime Component
- [x] Equipable Component
- [x] Weakness Position Component
- [x] IsCollidable Component
- [x] HitBox Size Component
- [x] BreakThrought Shot Component
- [x] Bouncing Shot Component
- [x] Damage Radius Component
- [x] Weight Component
- [x] IsInvincible Component
- [x] Player Component
- [x] EnemyComponent
- [x] Projectile Ally
- [x] Projectile Enemy
- [x] Projectile
- [x] Death Damage Component
- [x] IsInvisible Component
- [x] Obstacle Component
- [x] DeathComponent 
- [ ] Maybe another, please improve this issue and don't close it !

**Comment by TomDUVAL-MAHE** [comment]
Missing Components
