### ISSUE TITLE
Gravity System

### ISSUE THREAD

**Issue by TomDUVAL-MAHE** [R-Type-Epitech-Nantes/R-Type#78]
This issue is to create the Gravity System

This system need Components : 

1. Position
2. Weight
3. Velocity

This system need Shared Resources : 
1. Timer (Not create yet)

This force has the value P = m × g.
P is the intensity of the weight (in Newton). m is the mass (in kg). g is the gravitational intensity (in N/kg).

v = v₀ - g * t

v₀ is the initial velocity (m/s).

v is the final vertical speed (m/s).

h₀ is the initial altitude or distance with a object (m).

h is the altitude (m).

t is the elapsed time (s).

g is the acceleration due to gravity

**Comment by 31Nathan** [comment]
Not Done
